name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Build lib
        run: yarn run build
      - name: Publish to NPM
        uses: mikeal/merge-release@v4.0.7
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
